### ISSUE TITLE
signatory-ledger-cosval missing in readme

### ISSUE THREAD

**Issue by Liamsi** [tendermint/signatory#136]
Is this provider purposely left out from the readme?
https://github.com/tendermint/signatory/tree/master/providers/signatory-ledger-cosval

**Comment by tarcieri** [comment]
Nope, it just never got added

**Comment by jleni** [comment]
Now that the PR got merged, we can test a bit and I will add more info to the readme.

**Comment by Liamsi** [comment]
Will be addressed in #140

**Comment by jleni** [comment]
The provider has been renamed and included in the readme. We can close this issue.

**Comment by jleni** [comment]
@Liamsi @tarcieri  ^^^^

**Comment by Liamsi** [comment]
Thanks Juan!
