### ISSUE TITLE
How to get r, s, v from Asn1Signature(DER)?

### ISSUE THREAD

**Issue by yulidai** [tendermint/signatory#164]
Ask a question, maybe it's not about this library.

##### 1. What i want to do?
- Sign transactions of ETH by using Yubihsm 2

##### 2. How is the process now?
- I have get the signature of secp256k1(calculated by yubihsm2), it looks like this: `MEUCIQCsMU2QggMr1RzyOVBE80MXIt0H9CwuEhlUjZEeUyjWPgIgWcSgsTiAJxzyFb3am2GS3W5VT18oOvTTJUO0/1bYHvk=`, encoded with base64

##### 3. What's the problem?
- What i need is just to get `r`、`s`、`v` from `MEUCIQCsMU2QggMr1RzyOVBE80MXIt0H9CwuEhlUjZEeUyjWPgIgWcSgsTiAJxzyFb3am2GS3W5VT18oOvTTJUO0/1bYHvk=`, then I can say that the ETH signature was generated success.

Maybe the problem is simple, but it's not so easy for me. I hope I can get your help.   :)

**Comment by yulidai** [comment]
`r`, `s`, `v` are used for sign ETH transaction~

**Comment by yulidai** [comment]
maybe the problem can be simplified to `How to calculate v by using r and s`~

**Comment by tarcieri** [comment]
`v` is needed to recover the public key from the signature. Unfortunately recoverable signatures are not supported by the YubiHSM2.

Offhand I know of no libraries that allow you to compute the recovery ID from the YubiHSM2 output. The `secp256k1` crate supports recoverable signatures, but [the only way to get a recovery ID is during signing](https://docs.rs/libsecp256k1/0.2.2/secp256k1/fn.sign.html) AFAIK.
