### ISSUE TITLE
Crate fails to compile on Windows due to using `P::display()` on `P: AsRef<Path>`

### ISSUE THREAD

**Issue by str4d** [tendermint/signatory#180]
I'm currently trying to upgrade from 0.11. 0.12 has some other error on Windows. I get this error with both 0.13 and 0.16:

```
   Compiling signatory v0.16.0
error[E0599]: no method named `display` found for type `P` in the current scope
  --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\signatory-0.16.0\src\encoding\encode.rs:90:62
   |
90 |                 Some(&format!("couldn't create {}: {}", path.display(), e)),
   |                                                              ^^^^^^^

error[E0599]: no method named `display` found for type `P` in the current scope
   --> C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\signatory-0.16.0\src\encoding\pkcs8.rs:101:62
    |
101 |                 Some(&format!("couldn't create {}: {}", path.display(), e)),
    |                                                              ^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `signatory`.
warning: build failed, waiting for other jobs to finish...
error: build failed
PS C:\Users\me\Documents\dev\rust\ire> rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
```

0.12, 0.13, and 0.16 all compile fine on Ubuntu under WSL.

**Comment by str4d** [comment]
I don't immediately see an obvious reason for this. The failing code in question is compiled for `#[cfg(all(not(unix), feature = "std"))]`, but the corresponding `#[cfg(all(unix, feature = "std"))]` code has an equivalent formatting call with the same type bounds, and it compiles fine. I don't see any Unix-specific logic in the implementation of `Path::display()`.

**Comment by tarcieri** [comment]
This line is what's making the `unix` impl work:

https://github.com/tendermint/signatory/blob/develop/src/encoding/encode.rs#L59

It's missing from the other one. Unfortunately we have no Windows CI at the moment 😢
