### ISSUE TITLE
How to build an ECDSA public key from X509 PEM? 

### ISSUE THREAD

**Issue by leplatrem** [tendermint/signatory#181]
I am trying to verify an ECDSA signature (NIST384p curve, SHA384 hash).
The public key comes from a X509 PEM, and I cannot figure out to instantiate my `EcdsaPublicKey<NistP384>` from it.

In Python, with the `cryptography` library, I would just do this:
```py 
cert = cryptography.x509.load_pem_x509_certificate(cert_pem, default_backend())
public_key = cert.public_key()
# ... 
public_key.verify(signature, data, cryptography.hazmat.primitives.asymmetric.ec.ECDSA(SHA384()))
```
([example source](https://gist.github.com/leplatrem/9e95c5a41e235c74faa4c62fe4628357))

But with `signatory` I can't land on my feet :/
I've tried several things, but it always ends up on panicking :) 

```rust
    let x5u = "https://content-signature-2.cdn.mozilla.net/chains/pinning-preload.content-signature.mozilla.org-2019-12-24-21-43-28.chain";
    let signature_b64 = "80aDcD0HGWOoFHzKv3wMnfxMqgrb24Bz9G0w-87yDWaAIuj6vyCtybIl8lhE8gqmNPqSxPGCTpGqNiuW_J6_pZ2AyMRy_WN2l7asraSh5giBwKCXn6anOF8M2PsjNSi4";
    let data = r#"Content-Signature:\x00{"data":[],"last_modified":"1485794868067"}"#;

    // Fetch PEM
    let resp = reqwest::get(&x5u.to_string()).await?;
    let pem = resp.bytes().await?;
    // Parse PEM (OpenSSL)
    // Parse PEM (OpenSSL)
    let cert = X509::from_pem(&pem)?;
    let public_key = cert.public_key().unwrap();
    let der = public_key.public_key_to_der()?;
    let pk: EcdsaPublicKey<NistP384> = EcdsaPublicKey::from_untagged_point(GenericArray::from_slice(&der));

    // Instantiate signature
    let signature_bytes = base64::decode_config(&signature_b64, base64::URL_SAFE).unwrap();
    let signature = FixedSignature::<NistP384>::from_bytes(&signature_bytes).unwrap();

    // Verify
    let result = verify_sha384(&P384Verifier::from(&pk), &data.as_bytes(), &signature);
```

([example source](https://gist.github.com/leplatrem/b0c0d57fb6e8f4c445db3b0961d68b3c))

Does someone have an example that I could use as a reference? 

Once figured out, I'd happy to contribute some docs (eg. a cookbook section or whatever).

Thanks a lot for the great lib :pray: !

**Comment by leplatrem** [comment]
A friend helped me and we could get it work :)

I leave it here in case someone has something similar to do

```rust
    let x5u = "https://content-signature-2.cdn.mozilla.net/chains/pinning-preload.content-signature.mozilla.org-2019-12-24-21-43-28.chain";
    let signature_b64 = "80aDcD0HGWOoFHzKv3wMnfxMqgrb24Bz9G0w-87yDWaAIuj6vyCtybIl8lhE8gqmNPqSxPGCTpGqNiuW_J6_pZ2AyMRy_WN2l7asraSh5giBwKCXn6anOF8M2PsjNSi4";
    let data = "Content-Signature:\x00{\"data\":[],\"last_modified\":\"1485794868067\"}";

    // Fetch PEM
    let resp = reqwest::get(&x5u.to_string()).await?;
    let pem = resp.bytes().await?;
    // Parse PEM (OpenSSL)
    let cert = X509::from_pem(&pem)?;
    let openssl_public_key = cert.public_key().unwrap();
    let ec_public_key = openssl_public_key.ec_key().unwrap();
    // Convert to uncompressed bytes
    let mut ctx = BigNumContext::new().unwrap();
    let group = EcGroup::from_curve_name(Nid::SECP384R1).unwrap();
    let public_key_bytes = ec_public_key.public_key().to_bytes(&group, PointConversionForm::UNCOMPRESSED, &mut ctx).unwrap();
    // Instantiate signatory public key
    let pk: EcdsaPublicKey<NistP384> = EcdsaPublicKey::from_bytes(&public_key_bytes).unwrap();

    // Instantiate signature
    let signature_bytes = base64::decode_config(&signature_b64, base64::URL_SAFE).unwrap();
    let signature = FixedSignature::<NistP384>::from_bytes(&signature_bytes).unwrap();

    // Verify
    verify_sha384(&P384Verifier::from(&pk), &data.as_bytes(), &signature).unwrap();
```

**Comment by tarcieri** [comment]
Signatory does not (yet) support ASN.1 DER-encoded ECDSA public keys (offhand I'm not sure where they're specified, perhaps RFC5912)?

However, I believe after PEM decoding, for NIST P-384 it should be the last 97 bytes of the file, treated as a tagged public point.

**Comment by leplatrem** [comment]
> Signatory does not (yet) support ASN.1 DER-encoded ECDSA public keys (offhand I'm not sure where they're specified, perhaps RFC5912)?

You mean you would like to eventually provide the parsing features of openssl? 

There's this too https://tools.ietf.org/html/rfc5480

> However, I believe after PEM decoding, for NIST P-384 it should be the last 97 bytes of the file, treated as a tagged public point.

We could see that the first byte was `04`, and apparently uncompressed because we had 96 significant bits.

The signature verification posted above works BTW ;)

**Comment by tarcieri** [comment]
> You mean you would like to eventually provide the parsing features of openssl?

I would like to provide support for parsing this specific ASN.1 DER-encoded public key format.

> The signature verification posted above works BTW ;)

Yes, it'd be nice if it didn't require OpenSSL

**Comment by leplatrem** [comment]
> I would like to provide support for parsing this specific ASN.1 DER-encoded public key format.

I don't know if that helps, but this is how they were generated on the server side for the example I gave above:
https://github.com/mozilla-services/autograph/blob/master/signer/contentsignaturepki/x509.go#L64-L149
