### ISSUE TITLE
Validator Signing App on the Nano Ledger S

### ISSUE THREAD

**Issue by adrianbrink** [tendermint/signatory#60]
The work on implementing a validator signing app is tracked [here](https://docs.google.com/document/d/1pqVutp45uQbCETWEZwVknA3F4zrEHVy5c-SIpmNsBHo/edit).

**Comment by tarcieri** [comment]
I just released [signatory-ledger-cosval](https://crates.io/crates/signatory-ledger-cosval)

**Comment by tarcieri** [comment]
I think we can close this out now?

**Comment by tarcieri** [comment]
Aah, that'd probably make sense as I think the Signatory side of things is done with the release of `signatory-ledger-cosval`

**Comment by jleni** [comment]
for the moment, we will add more tests once the the firmware is ready
